// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RSGymClientManagment.Data;

#nullable disable

namespace RSGymClientManagment.Migrations
{
    [DbContext(typeof(ClientManagmentContext))]
    [Migration("20240813142318_02-SeedInitialData")]
    partial class _02SeedInitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RSGymClientManagment.Models.Clients", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"), 1L, 1);

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("IBAN")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("NIF")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            ClientName = "Rui Miguel Azevedo",
                            Email = "rma@mail.com",
                            IBAN = "PT50345678902345678901234",
                            NIF = "111111111",
                            Phone = "913456789",
                            Username = "rma1"
                        },
                        new
                        {
                            ClientId = 2,
                            ClientName = "Ana Dinis Silva",
                            Email = "ads@mail.com",
                            IBAN = "",
                            NIF = "222222222",
                            Phone = "917654321",
                            Username = "ads2"
                        });
                });

            modelBuilder.Entity("RSGymClientManagment.Models.Contracts", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractId"), 1L, 1);

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("Contract")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoyaltyId")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyFee")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ContractId");

                    b.HasIndex("ClientId");

                    b.HasIndex("LoyaltyId");

                    b.ToTable("Contracts");

                    b.HasData(
                        new
                        {
                            ContractId = 1,
                            ClientId = 1,
                            Contract = 0,
                            LoyaltyId = 1,
                            MonthlyFee = 50m,
                            StartDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ContractId = 2,
                            ClientId = 2,
                            Contract = 1,
                            EndDate = new DateTime(2024, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoyaltyId = 2,
                            MonthlyFee = 0m,
                            StartDate = new DateTime(2024, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("RSGymClientManagment.Models.ContractsGymClasses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<int>("GymClassId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("GymClassId");

                    b.ToTable("ContractsGymClasses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContractId = 1,
                            GymClassId = 1
                        },
                        new
                        {
                            Id = 2,
                            ContractId = 1,
                            GymClassId = 2
                        },
                        new
                        {
                            Id = 3,
                            ContractId = 1,
                            GymClassId = 3
                        },
                        new
                        {
                            Id = 4,
                            ContractId = 2,
                            GymClassId = 2
                        });
                });

            modelBuilder.Entity("RSGymClientManagment.Models.GymClasses", b =>
                {
                    b.Property<int>("GymClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GymClassId"), 1L, 1);

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ClassPrice")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("GymClassId");

                    b.ToTable("GymClasses");

                    b.HasData(
                        new
                        {
                            GymClassId = 1,
                            ClassName = "Yoga",
                            ClassPrice = 10m
                        },
                        new
                        {
                            GymClassId = 2,
                            ClassName = "Pilates",
                            ClassPrice = 15m
                        },
                        new
                        {
                            GymClassId = 3,
                            ClassName = "Body Strength",
                            ClassPrice = 20m
                        });
                });

            modelBuilder.Entity("RSGymClientManagment.Models.Loyalties", b =>
                {
                    b.Property<int>("LoyaltyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoyaltyId"), 1L, 1);

                    b.Property<decimal>("Discount")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("LoyaltyProgram")
                        .HasColumnType("bit");

                    b.HasKey("LoyaltyId");

                    b.ToTable("Loyalties");

                    b.HasData(
                        new
                        {
                            LoyaltyId = 1,
                            Discount = 10m,
                            LoyaltyProgram = true
                        },
                        new
                        {
                            LoyaltyId = 2,
                            Discount = 0m,
                            LoyaltyProgram = false
                        });
                });

            modelBuilder.Entity("RSGymClientManagment.Models.Payments", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"), 1L, 1);

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<decimal>("PaymentValue")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("PaymentId");

                    b.HasIndex("ContractId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            ContractId = 1,
                            PaymentDate = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentType = 2,
                            PaymentValue = 45m
                        },
                        new
                        {
                            PaymentId = 2,
                            ContractId = 2,
                            PaymentDate = new DateTime(2024, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentType = 0,
                            PaymentValue = 15m
                        });
                });

            modelBuilder.Entity("RSGymClientManagment.Models.Contracts", b =>
                {
                    b.HasOne("RSGymClientManagment.Models.Clients", "Client")
                        .WithMany("Contracts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RSGymClientManagment.Models.Loyalties", "Loyalty")
                        .WithMany("Contracts")
                        .HasForeignKey("LoyaltyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Loyalty");
                });

            modelBuilder.Entity("RSGymClientManagment.Models.ContractsGymClasses", b =>
                {
                    b.HasOne("RSGymClientManagment.Models.Contracts", "Contract")
                        .WithMany("ContractsGymClasses")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RSGymClientManagment.Models.GymClasses", "GymClass")
                        .WithMany("ContractsGymClasses")
                        .HasForeignKey("GymClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("GymClass");
                });

            modelBuilder.Entity("RSGymClientManagment.Models.Payments", b =>
                {
                    b.HasOne("RSGymClientManagment.Models.Contracts", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("RSGymClientManagment.Models.Clients", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("RSGymClientManagment.Models.Contracts", b =>
                {
                    b.Navigation("ContractsGymClasses");
                });

            modelBuilder.Entity("RSGymClientManagment.Models.GymClasses", b =>
                {
                    b.Navigation("ContractsGymClasses");
                });

            modelBuilder.Entity("RSGymClientManagment.Models.Loyalties", b =>
                {
                    b.Navigation("Contracts");
                });
#pragma warning restore 612, 618
        }
    }
}
